### ISSUE TITLE
search link to the eNanoMapper/AMBIT databases no longer working

### ISSUE THREAD

**Issue by egonw** [egonw/nmsa#3]
It used a URL pattern working at that time (`https://search.data.enanomapper.net/?search=CHEBI_51050`) but needs to be updated to the current pattern. Ideally, it would do a "federated" search in all databases, but obviously only show links for closed/embargoed data.

cc @vedina

**Comment by egonw** [comment]
see WGF notes for tip from Nick

**Comment by vedina** [comment]
https://search.data.enanomapper.net/projects/enanomapper/search?search=CHEBI_51050

**Comment by egonw** [comment]
@vedina, what I actually would like is a search like in the past, that would tell me which databases have search hits (possibly for the closed datasets just a search link redirect; of course, still applying current A&A!). With the purpose of encouraging collaboration between projects. Who knows, maybe asking access to the data becomes so common people give up in despair and just license it openly :) Or maybe they would just add the embargo information to the metadata, which would also be a step forward, imho

**Comment by egonw** [comment]
Updated.

**Comment by vedina** [comment]
@egonw , agree it will be useful,  but for the record the search never worked like you describe. 

each project has a Solr collection, which indexes several ambit databases ; then within a project one can search against all these databases;  but we never offered search against everything. 

though it is possible to have a metadata-only Solr collection to implement what you describe

**Comment by egonw** [comment]
> @egonw , agree it will be useful, but for the record the search never worked like you describe.

The meeting was a very long time ago, but I would be surprised if I had not tried the links to really work...

**Comment by vedina** [comment]
perhaps it was indeed very long ago, when only enanomapper public data was at that link ...
